### ISSUE TITLE
Evasion Roll in the Combat Tab linked to REF not DEX

### ISSUE THREAD

**Issue by jasntiamak** [mraichelson/cyberpunk-red-tabbed#29]
The evasion roll in the combat tab appears to be linked to a characters REF instead of the DEX skill.  I haven't found a usage of this in the book anywhere, so was wondering if it was an oops.

```
<button type="roll" value="&amp;{template:skill}{{charactername=@{character_name}}} {{skillname=Evasion}} {{skillvalue=@{skill_evasion}}} {{statname=REF}} {{statvalue=@{stat_ref}}} {{finalmodifier=@{finalmodifier}}} {{roll=[[1d10 + @{skill_evasion} + @{stat_ref} + @{armor_penalty} + @{finalmodifier} + @{evasionmodifier}]]}} {{critroll=[[1d10]]}}" class="btn ui-draggable">
                  Evasion
                </button>
```

**Comment by mraichelson** [comment]
D'oh! Good catch. I'll get a fix sorted out for this shortly.

**Comment by mraichelson** [comment]
Code change is in. I'll build another update to submit over the weekend. (Their review/merge process takes place on Mondays.)

**Comment by mraichelson** [comment]
Also: I did take a second to double-check that the Evasion button in the main Skills section is properly wired to DEX. This was just because the button in the Combat section is a one-off thing.

**Comment by mraichelson** [comment]
Sorry for letting this one slip. It's included in the PR that I just submitted here: https://github.com/Roll20/roll20-character-sheets/pull/8197
