### ISSUE TITLE
role_solo_precisionattack_calc not used in attack rolls

### ISSUE THREAD

**Issue by Harryc6** [mraichelson/cyberpunk-red-tabbed#34]
![image](https://user-images.githubusercontent.com/17144413/105713274-d7d45900-5f12-11eb-8f16-e912f2dde94b.png)
Enter as many points into Precision Attack to make sure you see the change.
![image](https://user-images.githubusercontent.com/17144413/105713126-a5c2f700-5f12-11eb-86f7-96ca3438dc8e.png)
Then roll attack on any weapon.
![image](https://user-images.githubusercontent.com/17144413/105713533-2d106a80-5f13-11eb-86b2-364677845205.png)
![image](https://user-images.githubusercontent.com/17144413/105713556-34377880-5f13-11eb-89e4-0a17f02895ad.png)

Potential fix - add text to say it needs to be tracked manually, or add @{role_solo_precisionattack_calc} to the attack roll (not too sure if that would throw a null if not init on character sheet, not familiar with roll20 variables)

**Comment by mraichelson** [comment]
This has been merged and will be included with the next update submitted to Roll20.

(Sorry for the confusion on my part about pushing changes to the PR around the hidden field, things got...weird.)

**Comment by mraichelson** [comment]
Included in the PR here: https://github.com/Roll20/roll20-character-sheets/pull/8197

My guess is that this will be checked as part of their monday morning review next week and then possibly make it to production towards the end of next week.
